/* Generated by the Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */

var framePtr = null;
var excHandler = 0;
var lastJSError = null;
if (typeof Int8Array === 'undefined') Int8Array = Array;
if (typeof Int16Array === 'undefined') Int16Array = Array;
if (typeof Int32Array === 'undefined') Int32Array = Array;
if (typeof Uint8Array === 'undefined') Uint8Array = Array;
if (typeof Uint16Array === 'undefined') Uint16Array = Array;
if (typeof Uint32Array === 'undefined') Uint32Array = Array;
if (typeof Float32Array === 'undefined') Float32Array = Array;
if (typeof Float64Array === 'undefined') Float64Array = Array;
var nimvm_6539 = false;
var nim_program_result = 0;
var globalRaiseHook_12005 = [null];
var localRaiseHook_12010 = [null];
var outOfMemHook_12013 = [null];
var objectID_53231 = [0];

function hello_68003() {
	var F={procname:"demo.hello",prev:framePtr,filename:"demo.nim",line:0};
	framePtr = F;
		F.line = 7;
		var doc_68005 = document;
		F.line = 8;
		var h_68006 = doc_68005.createElement("h1");
		F.line = 9;
		h_68006.appendChild(document.createTextNode("This heading was added from Nim"));
		F.line = 10;
		doc_68005.body.appendChild(h_68006);
	framePtr = F.prev;

	
}
module.exports.hello = hello_68003;
